### ISSUE TITLE
Custom Default Settings Recommendation

### ISSUE THREAD

**Issue by Colmines92** [vvanelslande/vvctre#139]
Hello, that's just a recommendation, if this doesn't go in this section, feel free to delete it.

Wouldn't it be easier for the program to simply save and load the configuration automatically into a configuration file, like your old builds, instead of creating a custom plugin for each user?

**Comment by vvanelslande** [comment]
that would make these plugins stop working
- custom default settings
- auto load controls
- themes
- 2DS switch
- MJPEG camera
