### ISSUE TITLE
Loading ROMs?

### ISSUE THREAD

**Issue by peteallelite** [vvanelslande/vvctre#19]
How on earth do you even load a ROM to use with it?

**Comment by vvanelslande** [comment]
https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/hotkeys/load-file-hotkey.lua

**Comment by peteallelite** [comment]
That does not answer my question. How about providing some sort of (even very brief) guide on how to specifically load a ROM

**Comment by vvanelslande** [comment]
## File menu, settings window, and load file hotkey

put the following scripts in vvctre's folder:
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/load-multiple-scripts/load-multiple-scripts-4.lua (file name: `script.lua`)
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/emulation-not-running/file-menu.lua (file name: `file-menu.lua`)
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/settings/settings-window.lua (file name: `settings-window.lua`)
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/hotkeys/load-file-hotkey.lua (file name: `load-file-hotkey.lua`)

## File menu and load file hotkey

put the following scripts in vvctre's folder:
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/load-multiple-scripts/load-multiple-scripts-5.lua (file name: `script.lua`)
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/emulation-not-running/file-menu.lua (file name: `file-menu.lua`)
- https://raw.githubusercontent.com/vvanelslande/vvctre-scripts/main/hotkeys/load-file-hotkey.lua (file name: `load-file-hotkey.lua`)

---

the load file hotkey script's default key is U

**Comment by peteallelite** [comment]
Thank you so much. Works great.
