### ISSUE TITLE
bypass required opengl level

### ISSUE THREAD

**Issue by FrostKnight** [vvanelslande/vvctre#232]
Would it be possible in the future to make an option for linux that allows you to bypass the required opengl level?
I have seen videos online of people being able to use citra with opengl 1.1 or opengl 2.1 in windows...
My request is that you could perhaps make it be able to work with opengl 2.0 or higher, you could even have it say buggy if it turns out to have any undesired effects that are not-safe.  

Just wanted to ask!  👍

**Comment by vvanelslande** [comment]
Windows: https://github.com/pal1000/mesa-dist-win
Linux: `LIBGL_ALWAYS_SOFTWARE=1 ./vvctre`

**Comment by FrostKnight** [comment]
Okay, I will try that... can this be added to wiki for future reference?

**Comment by vvanelslande** [comment]
added

**Comment by FrostKnight** [comment]
Thanks! :) close this issue then I guess :)
