### ISSUE TITLE
Window remains black

### ISSUE THREAD

**Issue by AndreMauriceB** [vvanelslande/vvctre#33]
Vvctre remains black, even in Windows' compatibility mode as admin.
My PC also meets all of the requirements written down on the wiki pages.
[Screenshot](https://user-images.githubusercontent.com/76048961/117123526-6de01100-ad97-11eb-8702-75ade2afde2e.png)

**Comment by vvanelslande** [comment]
https://github.com/vvanelslande/vvctre/issues/19#issuecomment-830868169
