### ISSUE TITLE
Trigger a rpc message to client on invalid memory reads and writes

### ISSUE THREAD

**Issue by hax0kartik** [vvanelslande/vvctre#6]
Hey, I was taking a look at the rpc capabilities and I think vvctre could potentially be used to search for bugs in games(dumb fuzzing) . You can already read/write memory  and set the hid pad state using different rpc endpoints. The only thing needed now is an api endpoint which stops the game execution whenever an invalid read/write occurs and triggers a message to the client.

The client code would roughly do this:-
1.)Randomize the savefile
2.)Write the file directly to the save array in memory
3.)Use the sethidstate endpoints to remotely control the game so it can load up the save( for eg:- for unholy heights you need to press A then down then an A to load up a save once you reach the main menu) 
4.) wait for any invalid reads or writes to occur.
5.) Somehow remotely restart the game using a new rpc endpoint and then repeat step 1 to 4. 

Tell me if you have any questions. Or you can contact me on discord Kartik#9392

**Comment by vvanelslande** [comment]
No need to add new endpoints.

> 4.) wait for any invalid reads or writes to occur.

vvctre logs invalid reads and writes, so you can start vvctre from your client and check for `: unmapped ` 
 in stderr.

> 5.) Somehow remotely restart the game using a new rpc endpoint and then repeat step 1 to 4.

to restart the game, you can use the [POST /usecpujit](https://github.com/vvanelslande/vvctre/blob/master/RPC.md#getpost-usecpujit) endpoint with body:
```json
{
  "enabled": true
}
```

**Comment by hax0kartik** [comment]
> vvctre logs invalid reads and writes, so you can start vvctre from your client and check for : unmapped in stderr.

Thanks for the reply, 
I would also like to stop/pause the current emulation once an invalid read/write happens. I don't think there is a way possible to do that using only the client?

**Comment by vvanelslande** [comment]
Endpoints to pause and continue emulation added in [6.9.0](https://github.com/vvanelslande/vvctre/releases/tag/v6.9.0)

**Comment by hax0kartik** [comment]
Thanks! Do you think you add an endpoint to read/write arm register values?

**Comment by vvanelslande** [comment]
Endpoints to get and set all the ARM register values added in [6.10.0](https://github.com/vvanelslande/vvctre/releases/tag/v6.10.0)

**Comment by vvanelslande** [comment]
Endpoint to only restart emulation added.
