### ISSUE TITLE
[Feature Request] New folder specifically for Preloading textures.

### ISSUE THREAD

**Issue by slentara1** [vvanelslande/vvctre#603]
I would like to suggest maybe pointing preload textures string to a new folder called preload as opposed to directing it to the load folder. That way we could portion off the textures we wish to load into the preload folder without loading ALL the textures.

See the example:
![unnamed](https://user-images.githubusercontent.com/67963757/105540523-f42a8880-5cbb-11eb-9943-587fe18e83a2.png)

**Comment by vvanelslande** [comment]
Added

**Comment by vvanelslande** [comment]
I added this
![](https://user-images.githubusercontent.com/62673824/105559288-be4acb80-5cde-11eb-87f0-671c8ae71046.png)
