### ISSUE TITLE
Not able to use Full Screen

### ISSUE THREAD

**Issue by Adamillo** [vvanelslande/vvctre#627]
I know how to go to full screen in Citra itself via F11 but on vvctre it doesn't work. Is there a different hotkey that enables full screen?
OS: Windows 10
CPU: Intel i5-7360U 2.30 GHz
RAM: 8 GB
GPU: Intel Iris Plus Graphics 640

**Comment by vvanelslande** [comment]
vvctre doesn't have fullscreen and I'll never add it
