### ISSUE TITLE
Custom Default Settings Plugin Request

### ISSUE THREAD

**Issue by MarooBardoo** [vvanelslande/vvctre#68]
audio.volume 0.500f
graphics.custom_textures enable
graphics.linear_filtering disable
graphics.resolution 4
graphics.texture_filter xBRZ freescale
layout.layout Medium Screen
multiplayer.nickname MarooBardoo

**Comment by vvanelslande** [comment]
https://github.com/vvanelslande/vvctre-plugin-settings-for-MarooBardoo/releases/tag/1.0.0
