### ISSUE TITLE
doesn't start on linux since 52.0.0

### ISSUE THREAD

**Issue by Idiot64** [vvanelslande/vvctre#846]
I get this output if it helps:

```[   0.000070] Input <Info> input_common/udp/client.cpp:StartCommunication:208: Starting communication with UDP input server on xxx.x.x.x:xxxxx```

x = [my publix ip numbers, i guess i dunno]

nothing happens after that..

**Comment by Idiot64** [comment]
It does make a black window tho

**Comment by vvanelslande** [comment]
https://github.com/vvanelslande/vvctre-scripts
