### ISSUE TITLE
build for macOS

### ISSUE THREAD

**Issue by azoreseuropa** [vvanelslande/vvctre#9]
Hi. I always build for Citra emu and I want to try this emulator. It looks interesting. The problem is that I got an error:

What I do is:

git clone https://github.com/vvanelslande/vvctre.git

cd vvctre
export Qt5_DIR=$(brew --prefix)/opt/qt5
mkdir build && cd build
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release

And error is:

-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/boost not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/nihstro not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/soundtouch not found.Please run: git submodule
  update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/catch not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/dynarmic not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/xbyak not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/cryptopp/cryptopp not found.Please run: git
  submodule update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/fmt not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/libressl not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/cubeb not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/teakra not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/semver not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/indicators not found.Please run: git submodule
  update --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/imgui not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

CMake Error at CMakeLists.txt:26 (message):
  Git submodule externals/clip not found.Please run: git submodule update
  --init --recursive
Call Stack (most recent call first):
  CMakeLists.txt:31 (check_submodules_present)

-- Target architecture: x86_64
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test CRYPTOPP_HAS_MSSE2
-- Performing Test CRYPTOPP_HAS_MSSE2 - Success
-- Performing Test CRYPTOPP_HAS_MSSSE3
-- Performing Test CRYPTOPP_HAS_MSSSE3 - Success
-- Performing Test CRYPTOPP_HAS_MSSE41
-- Performing Test CRYPTOPP_HAS_MSSE41 - Success
-- Performing Test CRYPTOPP_HAS_MSSE42
-- Performing Test CRYPTOPP_HAS_MSSE42 - Success
-- Performing Test CRYPTOPP_HAS_MAES
-- Performing Test CRYPTOPP_HAS_MAES - Success
-- Performing Test CRYPTOPP_HAS_PCLMUL
-- Performing Test CRYPTOPP_HAS_PCLMUL - Success
-- Performing Test CRYPTOPP_HAS_MSHA
-- Performing Test CRYPTOPP_HAS_MSHA - Success
-- Performing Test CRYPTOPP_HAS_ARMV8_CRC32
-- Performing Test CRYPTOPP_HAS_ARMV8_CRC32 - Failed
-- Performing Test CRYPTOPP_HAS_ARMV8_CRYPTO
-- Performing Test CRYPTOPP_HAS_ARMV8_CRYPTO - Failed
CMake Error at externals/CMakeLists.txt:20 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/dynarmic

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:24 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/fmt

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:25 (add_library):
  add_library cannot create ALIAS target "fmt::fmt" because target "fmt" does
  not already exist.

CMake Error at externals/CMakeLists.txt:38 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/soundtouch

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:40 (target_include_directories):
  Cannot specify include directories for target "SoundTouch" which is not
  built by this project.

CMake Error at externals/CMakeLists.txt:43 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/teakra

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:56 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/cubeb

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:61 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/libressl

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:62 (target_include_directories):
  Cannot specify include directories for target "ssl" which is not built by
  this project.

CMake Error at externals/CMakeLists.txt:63 (target_compile_definitions):
  Cannot specify compile definitions for target "ssl" which is not built by
  this project.

CMake Error at externals/CMakeLists.txt:108 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/clip

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:109 (target_include_directories):
  Cannot specify include directories for target "clip" which is not built by
  this project.

CMake Error at externals/CMakeLists.txt:111 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/semver

  does not contain a CMakeLists.txt file.

CMake Error at externals/CMakeLists.txt:113 (add_subdirectory):
  The source directory

    /Users/username/vvctre/externals/indicators

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/Users/username/vvctre/build/CMakeFiles/CMakeOutput.log".
See also "/Users/username/vvctre/build/CMakeFiles/CMakeError.log".

**Comment by vvanelslande** [comment]
it doesn't support macOS

**Comment by azoreseuropa** [comment]
That's too bad because Citra emu supported macOS great.
